import { useEffect, useState } from "react"; //hooks from React used for side effects and managing state.
import { useParams } from "react-router-dom"; //hook from react-router-dom that allows to access URL parameters
import { useGetPlaylistQuery } from "./PlaylistSlice"; //custom hook generated by Redux slice for fetching the playlist data from the backend.

export function PlayPlaylist() {
  //This is a component responsible for displaying and playing the selected playlist.
  const { id } = useParams(); //Retrieves the id parameter from the URL, which identifies the playlist to be played.
  const { data: playlist, error, isLoading } = useGetPlaylistQuery(id); //Fetches the playlist
  const [currentTrackIndex, setCurrentTrackIndex] = useState(0); //Sets current track state
  const [audio] = useState(new Audio()); //Creates an audio object: Initializes an Audio object to handle audio playback, which allows you to play and control audio tracks.

  useEffect(() => {
    //When the playlist is fetched and contains tracks, it sets the audio source to the URL of the current track and starts playing it.
    if (playlist && playlist.tracks.length > 0) {
      audio.src = playlist.tracks[currentTrackIndex].url; // Assume tracks have a 'url' property
      audio.play();
    }

    audio.addEventListener("ended", handleNextTrack); //Attaches an event listener to the audio object that calls handleNextTrack when the current track ends.

    return () => {
      //Cleanup function
      audio.removeEventListener("ended", handleNextTrack);
      audio.pause();
      audio.src = ""; // Clear the source
    };
  }, [playlist, currentTrackIndex, audio]); //When the component unmounts or when playlist, currentTrackIndex, or audio changes, the effect cleans up by removing the event listener, pausing the audio, and clearing the audio source.

  const handleNextTrack = () => {
    //Increments the currentTrackIndex to play the next track in the playlist. It uses modulo to loop back to the first track when reaching the end.
    setCurrentTrackIndex((prevIndex) => {
      const nextIndex = (prevIndex + 1) % playlist.tracks.length; // Loop back to start
      audio.src = playlist.tracks[nextIndex].url;
      audio.play();
      return nextIndex;
    });
  };

  const handlePreviousTrack = () => {
    //Decrements the currentTrackIndex to play the previous track. It ensures it loops back to the last track when at the beginning.
    setCurrentTrackIndex((prevIndex) => {
      const prevTrack =
        (prevIndex - 1 + playlist.tracks.length) % playlist.tracks.length; // Loop back to end
      audio.src = playlist.tracks[prevTrack].url;
      audio.play();
      return prevTrack;
    });
  };

  //Loading and error states:
  if (isLoading) return <p>Loading playlist...</p>;
  if (error) return <p>Error loading playlist: {error.message}</p>;

  return (
    //Renders the playlist and tracks
    <div>
      <h2>Playing Playlist: {playlist.name}</h2>
      <div>
        <h3>Tracks:</h3>
        <ul>
          {playlist.tracks.map((track, index) => (
            <li key={track.id}>
              {track.trackName} - {track.artistName}
              {currentTrackIndex === index && " (Now Playing)"}
            </li>
          ))}
        </ul>
        <button
          // Renders buttons for navigating between tracks. The "Previous" button is disabled if the first track is playing, and the "Next" button is disabled if the last track is playing.
          onClick={handlePreviousTrack}
          disabled={currentTrackIndex === 0}
        >
          Previous
        </button>
        <button
          onClick={handleNextTrack}
          disabled={currentTrackIndex === playlist.tracks.length - 1}
        >
          Next
        </button>
      </div>
    </div>
  );
}
